# render.yaml
services:
  - type: web
    name: nws-ml-api       # You can change this; it becomes part of your Render URL
    env: python
    region: oregon         # or frankfurt, virginia, etc.
    plan: free             # change to starter/standard if you need more memory
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT api:app
    autoDeploy: true

    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: API_TOKEN
        sync: false   # optional, lets you add a secret in Render dashboard
