name: Capture Predictions
on:
  schedule:
    # Runs at both possible times to handle DST changes
    - cron: '0 11 * * *'  # 7 AM EDT (Mar-Nov)
    - cron: '0 12 * * *'  # 7 AM EST (Nov-Mar)
    - cron: '0 23 * * *'  # 7 PM EDT (Mar-Nov)
    - cron: '0 0 * * *'   # 7 PM EST (Nov-Mar)
  workflow_dispatch:

jobs:
  capture:
    runs-on: ubuntu-latest
    steps:
      - name: Check if it's 7 AM or 7 PM ET and capture
        run: |
          # This will need logic to check current ET hour
          echo "Running capture check"
