name: Capture Predictions EST
on:
  schedule:
    - cron: '0 11 * * *'  # 7 AM EDT (11:00 UTC)
    - cron: '0 23 * * *'  # 7 PM EDT (23:00 UTC)
  workflow_dispatch:      # Manual trigger option

jobs:
  capture:
    runs-on: ubuntu-latest
    steps:
      - name: Capture and Log Predictions
        run: |
          set +e
          
          HOUR=$(TZ='America/New_York' date +%H)
          DATE=$(TZ='America/New_York' date +%Y-%m-%d)
          TOMORROW=$(TZ='America/New_York' date -d '+1 day' +%Y-%m-%d)
          TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)
          
          echo "Current ET hour: $HOUR"
          echo "Current ET date: $DATE"
          
          PREDICTIONS=$(curl -s https://app.dailydewpoint.com/)
          
PREDICTIONS=$(curl -s https://app.dailydewpoint.com/)

# Debug: Check if we're getting the right page
echo "=== Checking HTML content ==="
echo "$PREDICTIONS" | grep -c "prediction-value"
echo "$PREDICTIONS" | grep -o 'prediction-value[^>]*>[^<]*' | head -2

# Try multiple extraction patterns
echo "=== Trying extraction patterns ==="
# Pattern 1: With 째F
VALUES1=$(echo "$PREDICTIONS" | grep -o 'prediction-value">[0-9.]*째F' | sed 's/prediction-value">//g' | sed 's/째F//g')
echo "Pattern 1 results: $VALUES1"

# Pattern 2: Without 째F
VALUES2=$(echo "$PREDICTIONS" | grep -o 'prediction-value">[0-9.]*' | sed 's/prediction-value">//g')
echo "Pattern 2 results: $VALUES2"

# Pattern 3: With class=
VALUES3=$(echo "$PREDICTIONS" | grep -o 'class="prediction-value">[0-9.]*' | sed 's/class="prediction-value">//g')
echo "Pattern 3 results: $VALUES3"

# Use whichever worked
ALL_VALUES="${VALUES1:-${VALUES2:-$VALUES3}}"
VALUE_TODAY=$(echo "$ALL_VALUES" | head -1)
VALUE_TOMORROW=$(echo "$ALL_VALUES" | tail -1)

echo "Found values: TODAY=$VALUE_TODAY, TOMORROW=$VALUE_TOMORROW"
          
          echo "Found values: TODAY=$VALUE_TODAY, TOMORROW=$VALUE_TOMORROW"
          
          # Morning: 7 AM ET
          if [ "$HOUR" = "07" ]; then
            echo "7 AM ET - Capturing morning predictions"
            
            if [ ! -z "$VALUE_TODAY" ]; then
              curl -s -X POST https://app.dailydewpoint.com/api/log-prediction-snapshot \
                -H "Content-Type: application/json" \
                -d "{\"target_date\":\"$DATE\",\"prediction_type\":\"morning_of\",\"prediction_value\":$VALUE_TODAY,\"snapshot_time\":\"$TIMESTAMP\"}"
              echo "Logged morning_of: $VALUE_TODAY"
            fi
            
            if [ ! -z "$VALUE_TOMORROW" ]; then
              curl -s -X POST https://app.dailydewpoint.com/api/log-prediction-snapshot \
                -H "Content-Type: application/json" \
                -d "{\"target_date\":\"$TOMORROW\",\"prediction_type\":\"day_before_morning\",\"prediction_value\":$VALUE_TOMORROW,\"snapshot_time\":\"$TIMESTAMP\"}"
              echo "Logged day_before_morning: $VALUE_TOMORROW"
            fi
            
          # Evening: 7 PM ET
          elif [ "$HOUR" = "19" ]; then
            echo "7 PM ET - Capturing evening prediction"
            
            if [ ! -z "$VALUE_TOMORROW" ]; then
              curl -s -X POST https://app.dailydewpoint.com/api/log-prediction-snapshot \
                -H "Content-Type: application/json" \
                -d "{\"target_date\":\"$TOMORROW\",\"prediction_type\":\"night_before\",\"prediction_value\":$VALUE_TOMORROW,\"snapshot_time\":\"$TIMESTAMP\"}"
              echo "Logged night_before: $VALUE_TOMORROW"
            fi
            
          # Manual trigger
          else
            echo "Manual trigger or off-schedule run"
            if [ "$HOUR" -ge "6" ] && [ "$HOUR" -le "10" ]; then
              echo "Morning hours - running morning capture"
              
              if [ ! -z "$VALUE_TODAY" ]; then
                curl -s -X POST https://app.dailydewpoint.com/api/log-prediction-snapshot \
                  -H "Content-Type: application/json" \
                  -d "{\"target_date\":\"$DATE\",\"prediction_type\":\"morning_of\",\"prediction_value\":$VALUE_TODAY,\"snapshot_time\":\"$TIMESTAMP\"}"
                echo "Logged morning_of: $VALUE_TODAY"
              fi
              
              if [ ! -z "$VALUE_TOMORROW" ]; then
                curl -s -X POST https://app.dailydewpoint.com/api/log-prediction-snapshot \
                  -H "Content-Type: application/json" \
                  -d "{\"target_date\":\"$TOMORROW\",\"prediction_type\":\"day_before_morning\",\"prediction_value\":$VALUE_TOMORROW,\"snapshot_time\":\"$TIMESTAMP\"}"
                echo "Logged day_before_morning: $VALUE_TOMORROW"
              fi
              
            elif [ "$HOUR" -ge "18" ] && [ "$HOUR" -le "21" ]; then
              echo "Evening hours - running evening capture"
              
              if [ ! -z "$VALUE_TOMORROW" ]; then
                curl -s -X POST https://app.dailydewpoint.com/api/log-prediction-snapshot \
                  -H "Content-Type: application/json" \
                  -d "{\"target_date\":\"$TOMORROW\",\"prediction_type\":\"night_before\",\"prediction_value\":$VALUE_TOMORROW,\"snapshot_time\":\"$TIMESTAMP\"}"
                echo "Logged night_before: $VALUE_TOMORROW"
              fi
            fi
          fi
