name: Capture Predictions EST
on:
  schedule:
    - cron: '0 12 * * *'  # 7 AM EST (noon UTC)
    - cron: '0 0 * * *'   # 7 PM EST (midnight UTC)
  workflow_dispatch:      # Allows manual trigger from GitHub UI
jobs:
  capture:
    runs-on: ubuntu-latest
    steps:
      - name: Capture and Log Predictions
        run: |
          set +e  # Turn off exit-on-error
          
          # Get current hour in Eastern Time
          HOUR=$(TZ='America/New_York' date +%H)
          DATE=$(TZ='America/New_York' date +%Y-%m-%d)
          
          echo "Current ET hour: $HOUR"
          echo "Current ET date: $DATE"
          
          # Fetch current predictions from your dashboard
          echo "Fetching predictions from dashboard..."
          PREDICTIONS=$(curl -s https://app.dailydewpoint.com/)
          
          if [ "$HOUR" = "07" ]; then
            echo "7 AM EST - Capturing both today and tomorrow predictions"
            
            # Extract today's prediction value from HTML (try multiple patterns)
            VALUE_TODAY=$(echo "$PREDICTIONS" | grep -oP 'correctionBoxToday.*?(\d+\.\d+)째F' | head -1 | grep -oP '\d+\.\d+')
            if [ -z "$VALUE_TODAY" ]; then
              VALUE_TODAY=$(echo "$PREDICTIONS" | grep -oP 'prediction-value[^>]*>(\d+\.\d+)' | grep -oP '\d+\.\d+' | head -1)
            fi
            
            echo "Today's value: $VALUE_TODAY"
            
            # Log today's morning_of prediction if found
            if [ ! -z "$VALUE_TODAY" ]; then
              curl -s -X POST https://app.dailydewpoint.com/api/log-prediction-snapshot \
                -H "Content-Type: application/json" \
                -d "{\"target_date\":\"$DATE\",\"prediction_type\":\"morning_of\",\"prediction_value\":$VALUE_TODAY,\"snapshot_time\":\"$(TZ='America/New_York' date +%Y-%m-%dT%H:%M:%S)\"}"
              echo "Logged morning_of: $VALUE_TODAY"
            fi
            
            # Get tomorrow's date and prediction
            TOMORROW=$(TZ='America/New_York' date -d '+1 day' +%Y-%m-%d)
            VALUE_TOMORROW=$(echo "$PREDICTIONS" | grep -oP 'correctionBoxTomorrow.*?(\d+\.\d+)째F' | head -1 | grep -oP '\d+\.\d+')
            if [ -z "$VALUE_TOMORROW" ]; then
              VALUE_TOMORROW=$(echo "$PREDICTIONS" | grep -oP 'prediction-value[^>]*>(\d+\.\d+)' | grep -oP '\d+\.\d+' | tail -1)
            fi
            
            echo "Tomorrow's value: $VALUE_TOMORROW"
            
            # Log tomorrow's day_before_morning prediction if found
            if [ ! -z "$VALUE_TOMORROW" ]; then
              curl -s -X POST https://app.dailydewpoint.com/api/log-prediction-snapshot \
                -H "Content-Type: application/json" \
                -d "{\"target_date\":\"$TOMORROW\",\"prediction_type\":\"day_before_morning\",\"prediction_value\":$VALUE_TOMORROW,\"snapshot_time\":\"$(TZ='America/New_York' date +%Y-%m-%dT%H:%M:%S)\"}"
              echo "Logged day_before_morning: $VALUE_TOMORROW"
            fi
            
          elif [ "$HOUR" = "19" ]; then
            echo "7 PM EST - Capturing night_before prediction for tomorrow"
            
            # Get tomorrow's date
            TOMORROW=$(TZ='America/New_York' date -d '+1 day' +%Y-%m-%d)
            
            # Try multiple extraction patterns
            VALUE=$(echo "$PREDICTIONS" | grep -oP 'correctionBoxTomorrow.*?(\d+\.\d+)째F' | head -1 | grep -oP '\d+\.\d+')
            if [ -z "$VALUE" ]; then
              VALUE=$(echo "$PREDICTIONS" | grep -oP 'prediction-value[^>]*>(\d+\.\d+)' | grep -oP '\d+\.\d+' | tail -1)
            fi
            if [ -z "$VALUE" ]; then
              VALUE=$(echo "$PREDICTIONS" | grep -oP '\d+\.\d+(?=째F)' | tail -1)
            fi
            
            echo "Extracted value: $VALUE"
            
            # Only log if we have a value
            if [ ! -z "$VALUE" ]; then
              curl -s -X POST https://app.dailydewpoint.com/api/log-prediction-snapshot \
                -H "Content-Type: application/json" \
                -d "{\"target_date\":\"$TOMORROW\",\"prediction_type\":\"night_before\",\"prediction_value\":$VALUE,\"snapshot_time\":\"$(TZ='America/New_York' date +%Y-%m-%dT%H:%M:%S)\"}"
              echo "Logged night_before: $VALUE for $TOMORROW"
            else
              echo "ERROR: Could not extract value, skipping"
            fi
            
          else
            echo "Not scheduled capture time (hour is $HOUR, expecting 07 or 19)"
          fi
