name: Capture Predictions EST
on:
  schedule:
    - cron: '0 12 * * *'  # 7 AM EST
    - cron: '0 0 * * *'   # 7 PM EST
  workflow_dispatch:

jobs:
  capture:
    runs-on: ubuntu-latest
    steps:
      - name: Capture Predictions
        run: |
          HOUR=$(TZ='America/New_York' date +%H)
          DATE=$(TZ='America/New_York' date +%Y-%m-%d)
          
          # Fetch current predictions from your dashboard
          PREDICTIONS=$(curl -s https://app.dailydewpoint.com/)
          
          if [ "$HOUR" = "07" ]; then
            # Extract today's prediction and log as morning_of
            VALUE=$(echo "$PREDICTIONS" | grep -oP 'correctionBoxToday.*?(\d+\.\d+)°F' | head -1 | grep -oP '\d+\.\d+')
            
            curl -X POST https://app.dailydewpoint.com/api/log-prediction-snapshot \
              -H "Content-Type: application/json" \
              -d "{\"target_date\":\"$DATE\",\"prediction_type\":\"morning_of\",\"prediction_value\":$VALUE,\"snapshot_time\":\"$(date -u +%Y-%m-%dT%H:%M:%S)Z\"}"
              
          elif [ "$HOUR" = "19" ]; then
            # Extract tomorrow's prediction and log as night_before
            TOMORROW=$(TZ='America/New_York' date -d '+1 day' +%Y-%m-%d)
            VALUE=$(echo "$PREDICTIONS" | grep -oP 'correctionBoxTomorrow.*?(\d+\.\d+)°F' | head -1 | grep -oP '\d+\.\d+')
            
            curl -X POST https://app.dailydewpoint.com/api/log-prediction-snapshot \
              -H "Content-Type: application/json" \
              -d "{\"target_date\":\"$TOMORROW\",\"prediction_type\":\"night_before\",\"prediction_value\":$VALUE,\"snapshot_time\":\"$(date -u +%Y-%m-%dT%H:%M:%S)Z\"}"
          fi
