name: Capture Predictions EST
on:
  schedule:
    - cron: '0 12 * * *'  # 7 AM EST
    - cron: '0 0 * * *'   # 7 PM EST
  workflow_dispatch:

jobs:
  capture:
    runs-on: ubuntu-latest
    steps:
      - name: Capture Predictions
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: |
          HOUR=$(TZ='America/New_York' date +%H)
          DATE=$(TZ='America/New_York' date +%Y-%m-%d)
          
          if [ "$HOUR" = "07" ]; then
            # 7 AM - Morning of prediction for today
            curl -X POST https://app.dailydewpoint.com/api/auto-capture \
              -H "Authorization: Bearer $AUTH_TOKEN" \
              -H "Content-Type: application/json" \
              -d "{\"type\":\"morning_of\",\"target_date\":\"$DATE\"}"
          elif [ "$HOUR" = "19" ]; then
            # 7 PM - Night before prediction for tomorrow
            TOMORROW=$(TZ='America/New_York' date -d '+1 day' +%Y-%m-%d)
            curl -X POST https://app.dailydewpoint.com/api/auto-capture \
              -H "Authorization: Bearer $AUTH_TOKEN" \
              -H "Content-Type: application/json" \
              -d "{\"type\":\"night_before\",\"target_date\":\"$TOMORROW\"}"
          fi
