name: Capture Predictions
on:
  schedule:
    - cron: '0 12 * * *'  # 7 AM ET (noon UTC)
    - cron: '0 0 * * *'   # 7 PM ET (midnight UTC)
  workflow_dispatch:      # Allows manual trigger from GitHub

jobs:
  capture:
    runs-on: ubuntu-latest
    steps:
      - name: Capture Morning Prediction (7 AM ET)
        if: github.event.schedule == '0 12 * * *'
        run: |
          echo "Running 7 AM capture"
          # You'll need to create this API endpoint
          curl -X POST https://app.dailydewpoint.com/api/capture-morning
          
      - name: Capture Evening Prediction (7 PM ET)
        if: github.event.schedule == '0 0 * * *'
        run: |
          echo "Running 7 PM capture"
          # You'll need to create this API endpoint
          curl -X POST https://app.dailydewpoint.com/api/capture-evening
