name: Update Kalshi Winner JSON

on:
  workflow_dispatch:
  schedule:
    # Every 15 minutes
    - cron: "*/15 * * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Fetch Kalshi winner
        run: |
          python scripts/fetch_kalshi_winner.py

      - name: Commit JSON (if changed)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update kalshi_winner.json"
          file_pattern: public/kalshi_winner.json
