name: NWS Auto Logger

on:
  schedule:
    # Runs every day at 23:30 UTC (7:30 PM ET / 6:30 PM EST)
    - cron: "30 23 * * *"
  workflow_dispatch:  # allow manual run from Actions tab

jobs:
  run-logger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Run logger
        run: python run_once.py

      - name: Commit & push CSV
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add nws_forecast_log.csv
          git commit -m "Update forecast log [skip ci]" || echo "No changes"
          git push
